export enum UserFormEnum {
  FIRST_NAME = 'firstName',
  LAST_NAME = 'lastName',
  DATE_OF_BIRTH = 'dateOfBirth',
  STREET = 'street',
  CITY = 'city',
  POSTAL_CODE = 'postalCode',
  DEFAULT_ADDRESS = 'defaultAddress',
  DIFFERENT_BILLING = 'differentBilling',
  STREET_BILLING = 'streetBilling',
  CITY_BILLING = 'cityBilling',
  POSTAL_CODE_BILLING = 'postalCodeBilling',
  DEFAULT_BILLING = 'defaultBilling',
  EMAIL = 'email',
  PASSWORD = 'Password',
}
